name: sekerme_ecommerce
description: E-commerce app for product sales.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Go Router Un paquete de enrutamiento declarativo para Flutter
  go_router: ^9.0.3
  #flutte native splash Un paquete para generar el código nativo de Android y iOS para personalizar la pantalla de inicio de su aplicación.
  flutter_native_splash: ^2.3.1
  # flutter_launcher_icons Un paquete que personaliza el ícono de la aplicación tanto para iOS como para Android.
  flutter_launcher_icons: ^0.13.1
  # Bloc Un paquete de administración de estado inspirado en Redux para Flutter
  bloc: ^8.1.2
  # Flutter Bloc Un paquete de administración de estado inspirado en Redux para Flutter
  flutter_bloc: ^8.1.3
  # equatable Un paquete de utilidad para comparar objetos en Dart.
  equatable: ^2.0.5
  # flutter_svg Un paquete que proporciona un widget SVG para Flutter
  flutter_svg: ^2.0.7
  # Supabase Un paquete de Flutter que proporciona una API de plataforma unificada para autenticación,
  # Cloud Firestore, Cloud Functions, Cloud Messaging, Cloud Storage, Remote Config y más.
  supabase_flutter: ^1.10.10
  #flutter_dotenv Un paquete que proporciona una API de plataforma unificada para autenticación,
  flutter_dotenv: ^5.1.0
  # intl Un paquete que proporciona una API de plataforma unificada para autenticación,
  intl: ^0.18.1
  # crypto paquete de encriptación de datos
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/global/

  fonts:
    - family: Odin Rounded
      fonts:
        - asset: assets/fonts/OdinRounded/Odin Rounded - Regular.otf
        - asset: assets/fonts/OdinRounded/Odin Rounded - Regular Italic.otf
        - asset: assets/fonts/OdinRounded/Odin Rounded - Bold.otf
        - asset: assets/fonts/OdinRounded/Odin Rounded - Bold Italic.otf
        - asset: assets/fonts/OdinRounded/Odin Rounded - Light.otf
        - asset: assets/fonts/OdinRounded/Odin Rounded - Light Italic.otf


